window.aiDemoAnswers = [
  {
    id: "abnormal-region",
    title: "经营异常企业按区域统计",
    keywords: ["经营异常", "异常名录", "区域", "行政区", "企业", "统计"],
    source: "企业经营异常名录",
    creator: "工商核查",
    createdAt: "2026-08-03 11:05",
    chartTitle: "经营异常企业区域分布",
    defaultChart: "bar",
    displayCharts: ["bar"],
    tableHeaders: ["序号", "区域", "异常企业数量（家）"],
    chartData: [
      { label: "白云区", value: 7, group: "异常", columns: ["1", "白云区", "7"] },
      { label: "番禺区", value: 5, group: "异常", columns: ["2", "番禺区", "5"] },
      { label: "天河区", value: 4, group: "异常", columns: ["3", "天河区", "4"] },
      { label: "黄埔区", value: 3, group: "异常", columns: ["4", "黄埔区", "3"] },
      { label: "南沙区", value: 2, group: "异常", columns: ["5", "南沙区", "2"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "当前样例库共识别到5个区域存在经营异常企业，其中白云区数量最高，为7家；番禺区次之，为5家。",
      },
      {
        heading: "二、处理建议",
        bullets: [
          "优先核查异常数量较高区域的企业地址、年报和经营状态。",
          "对连续异常或多次异常企业增加风险标签。",
          "结合行业和注册资本继续判断异常企业的影响范围。",
        ],
      },
    ],
    guesses: [
      { label: "列出白云区异常企业", body: "可输出白云区异常企业名称、法人、异常原因、列入日期和处理状态。", chart: "table" },
      { label: "异常原因占比", body: "可按未按时年报、住所失联、公示信息异常等原因统计占比。", chart: "pie" },
      { label: "按行业看异常分布", body: "建议按批发零售、商务服务、建筑装饰、居民服务等行业拆分异常企业数量。", chart: "bar" },
    ],
  },
  {
    id: "license-expiry",
    title: "证照即将到期企业提醒",
    keywords: ["证照", "到期", "许可证", "企业", "提醒", "清单"],
    source: "行政许可与证照台账",
    creator: "工商核查",
    createdAt: "2026-08-03 11:12",
    chartTitle: "证照到期时间分布",
    defaultChart: "table",
    displayCharts: ["table"],
    tableHeaders: ["序号", "企业名称", "证照类型", "到期日期", "剩余天数", "责任人"],
    chartData: [
      { label: "穗安食品贸易有限公司", value: 12, group: "食品经营许可", columns: ["1", "穗安食品贸易有限公司", "食品经营许可", "2026-08-15", "12", "周敏"] },
      { label: "越海运输服务有限公司", value: 18, group: "道路运输许可", columns: ["2", "越海运输服务有限公司", "道路运输许可", "2026-08-21", "18", "陈浩"] },
      { label: "南岭医疗器械有限公司", value: 27, group: "器械备案", columns: ["3", "南岭医疗器械有限公司", "器械备案", "2026-08-30", "27", "李珊"] },
      { label: "东泽广告工程有限公司", value: 41, group: "施工备案", columns: ["4", "东泽广告工程有限公司", "施工备案", "2026-09-13", "41", "王磊"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "当前共有4家企业存在证照即将到期提醒，其中2家企业剩余天数少于20天，需要优先处理。",
      },
      {
        heading: "二、处理建议",
        bullets: [
          "剩余30天以内证照进入续期跟进清单。",
          "剩余20天以内证照每日确认材料准备状态。",
          "证照续期完成后同步更新证照台账和责任人记录。",
        ],
      },
    ],
    guesses: [
      { label: "只看20天内到期", body: "20天内到期的企业为穗安食品贸易有限公司和越海运输服务有限公司，建议优先确认续期材料。", chart: "table" },
      { label: "按证照类型统计", body: "可按食品经营许可、道路运输许可、器械备案、施工备案等类型查看到期分布。", chart: "bar" },
      { label: "生成续期跟进表", body: "续期跟进表建议包含企业名称、证照类型、到期日期、责任人、材料状态和预计提交日期。", chart: "table" },
    ],
  },
  {
    id: "legal-change",
    title: "近一年法人变更企业统计",
    keywords: ["法人变更", "法人", "变更", "近一年", "企业", "统计"],
    source: "企业变更登记记录",
    creator: "工商核查",
    createdAt: "2026-08-03 11:18",
    chartTitle: "近一年法人变更月度统计",
    defaultChart: "bar",
    displayCharts: ["bar"],
    tableHeaders: ["序号", "月份", "法人变更企业数量（家）"],
    chartData: [
      { label: "9月", value: 1, group: "2025", columns: ["1", "2025年9月", "1"] },
      { label: "10月", value: 2, group: "2025", columns: ["2", "2025年10月", "2"] },
      { label: "11月", value: 1, group: "2025", columns: ["3", "2025年11月", "1"] },
      { label: "12月", value: 3, group: "2025", columns: ["4", "2025年12月", "3"] },
      { label: "1月", value: 2, group: "2026", columns: ["5", "2026年1月", "2"] },
      { label: "2月", value: 1, group: "2026", columns: ["6", "2026年2月", "1"] },
      { label: "3月", value: 4, group: "2026", columns: ["7", "2026年3月", "4"] },
      { label: "4月", value: 2, group: "2026", columns: ["8", "2026年4月", "2"] },
      { label: "5月", value: 3, group: "2026", columns: ["9", "2026年5月", "3"] },
      { label: "6月", value: 2, group: "2026", columns: ["10", "2026年6月", "2"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "近一年法人变更记录在2026年3月出现小高峰，当月涉及4家企业。整体来看，法人变更呈零散分布。",
      },
      {
        heading: "二、核查建议",
        bullets: [
          "重点查看法人变更后是否同步发生股东或地址变更。",
          "对短期多次变更企业增加核查优先级。",
          "结合经营状态和异常名录判断变更风险。",
        ],
      },
    ],
    guesses: [
      { label: "列出3月变更企业", body: "可输出2026年3月法人变更企业的名称、原法人、新法人、变更日期和登记机关。", chart: "table" },
      { label: "按季度汇总法人变更", body: "可将月度变更数据按季度汇总，查看法人变更是否集中在特定周期。", chart: "bar" },
      { label: "法人变更原因有哪些", body: "常见原因包括股权调整、管理层更换、企业重组、工商信息纠错等。", chart: "pie" },
    ],
  },
  {
    id: "paid-capital",
    title: "实缴资本为0企业清单",
    keywords: ["实缴资本", "0", "企业", "认缴", "清单", "资本"],
    source: "企业资本登记数据",
    creator: "工商核查",
    createdAt: "2026-08-03 11:24",
    chartTitle: "实缴资本为0企业明细",
    defaultChart: "table",
    displayCharts: ["table"],
    tableHeaders: ["序号", "企业名称", "注册资本（元）", "实缴资本（元）", "成立日期", "经营状态"],
    chartData: [
      { label: "广州青禾科技有限公司", value: 0, group: "存续", columns: ["1", "广州青禾科技有限公司", "2,000,000.00", "0.00", "2024-03-12", "存续"] },
      { label: "穗北文化传媒有限公司", value: 0, group: "存续", columns: ["2", "穗北文化传媒有限公司", "500,000.00", "0.00", "2023-11-08", "存续"] },
      { label: "海睿供应链管理有限公司", value: 0, group: "存续", columns: ["3", "海睿供应链管理有限公司", "3,000,000.00", "0.00", "2025-06-19", "存续"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "当前样例库中共有3家企业实缴资本为0，且经营状态均为存续。",
      },
      {
        heading: "二、分析说明",
        bullets: [
          "实缴资本为0不等于经营异常，需要结合认缴期限和经营状态判断。",
          "若企业同时存在异常名录、地址失联或高频变更，需要提高关注级别。",
          "可继续核查股东出资时间和实缴变更记录。",
        ],
      },
    ],
    guesses: [
      { label: "按注册资本排序", body: "海睿供应链管理有限公司注册资本最高，为300万元；广州青禾科技有限公司为200万元。", chart: "bar" },
      { label: "补充股东认缴期限", body: "可输出股东姓名、认缴金额、认缴期限和实缴状态，形成资本穿透表。", chart: "table" },
      { label: "筛选成立超过2年", body: "可叠加成立时间条件，优先核查成立较久但实缴仍为0的企业。", chart: "table" },
    ],
  },
  {
    id: "insured-scale",
    title: "参保人数区间分布",
    keywords: ["参保人数", "社保", "人数区间", "企业", "分布", "统计"],
    source: "企业年报参保数据",
    creator: "工商核查",
    createdAt: "2026-08-03 11:30",
    chartTitle: "企业参保人数区间分布",
    defaultChart: "pie",
    displayCharts: ["pie"],
    tableHeaders: ["序号", "参保人数区间", "企业数量（家）"],
    chartData: [
      { label: "0人", value: 6, group: "无参保", columns: ["1", "0人", "6"] },
      { label: "1-5人", value: 8, group: "小规模", columns: ["2", "1-5人", "8"] },
      { label: "6-20人", value: 5, group: "成长型", columns: ["3", "6-20人", "5"] },
      { label: "21-50人", value: 2, group: "中型", columns: ["4", "21-50人", "2"] },
      { label: "50人以上", value: 1, group: "较大规模", columns: ["5", "50人以上", "1"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "参保人数集中在1-5人和0人区间，说明样例企业以小规模主体为主。",
      },
      {
        heading: "二、数据解读",
        bullets: [
          "参保人数为0的企业需要结合经营状态和年报情况判断活跃度。",
          "1-5人区间企业可进一步按行业和区域拆分。",
          "50人以上企业数量较少，可作为重点企业单独查看。",
        ],
      },
    ],
    guesses: [
      { label: "列出参保为0企业", body: "可输出参保人数为0的企业名称、行业、注册资本、经营状态和年报年份。", chart: "table" },
      { label: "按行业看参保区间", body: "可将参保人数区间与行业交叉分析，判断小规模主体主要集中在哪些行业。", chart: "bar" },
      { label: "找出50人以上企业", body: "可单独列出50人以上企业，核对其注册资本、成立年限和所在区域。", chart: "table" },
    ],
  },
  {
    id: "address-cluster",
    title: "同地址注册企业数量排查",
    keywords: ["同地址", "注册地址", "集群", "企业数量", "地址", "排查"],
    source: "企业注册地址数据",
    creator: "工商核查",
    createdAt: "2026-08-03 11:36",
    chartTitle: "同地址注册企业数量",
    defaultChart: "bar",
    displayCharts: ["bar"],
    tableHeaders: ["序号", "注册地址", "企业数量（家）", "主要行业"],
    chartData: [
      { label: "科汇园A座", value: 12, group: "园区", columns: ["1", "科汇园A座", "12", "科技服务"] },
      { label: "创智路18号", value: 9, group: "园区", columns: ["2", "创智路18号", "9", "商贸服务"] },
      { label: "云港大厦", value: 6, group: "写字楼", columns: ["3", "云港大厦", "6", "商务服务"] },
      { label: "南湾产业园", value: 5, group: "园区", columns: ["4", "南湾产业园", "5", "制造服务"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "科汇园A座同地址注册企业数量最高，共12家；创智路18号有9家。",
      },
      {
        heading: "二、核查建议",
        bullets: [
          "同地址注册不一定异常，园区、众创空间和集中办公区较常见。",
          "若同地址企业同时存在同法人、同电话或经营异常，需要进一步核查。",
          "可结合地址类型、行业和成立时间判断是否为集中注册。",
        ],
      },
    ],
    guesses: [
      { label: "展开科汇园企业明细", body: "可输出科汇园A座下企业名称、法人、行业、注册时间和经营状态。", chart: "table" },
      { label: "同地址企业占比", body: "可将同地址企业按地址聚合后生成占比图，查看集中程度。", chart: "pie" },
      { label: "筛选同法人同地址", body: "可叠加法人姓名条件，排查同一法人名下集中注册情况。", chart: "table" },
    ],
  },
  {
    id: "contact-missing",
    title: "企业联系电话缺失情况",
    keywords: ["联系电话", "电话", "缺失", "企业", "联系方式", "统计"],
    source: "企业联系方式台账",
    creator: "工商核查",
    createdAt: "2026-08-03 11:42",
    chartTitle: "联系电话缺失类型统计",
    defaultChart: "bar",
    displayCharts: ["bar"],
    tableHeaders: ["序号", "缺失类型", "企业数量（家）"],
    chartData: [
      { label: "联系电话为空", value: 8, group: "缺失", columns: ["1", "联系电话为空", "8"] },
      { label: "号码格式错误", value: 3, group: "错误", columns: ["2", "号码格式错误", "3"] },
      { label: "号码重复", value: 4, group: "重复", columns: ["3", "号码重复", "4"] },
      { label: "号码停用", value: 2, group: "失效", columns: ["4", "号码停用", "2"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "联系电话为空的问题最多，共8家企业；号码重复和格式错误也需要清理。",
      },
      {
        heading: "二、治理建议",
        bullets: [
          "先补齐联系电话为空的企业。",
          "对号码格式错误进行规则校验和统一格式化。",
          "对重复号码结合法人、地址和企业关系判断是否合理。",
        ],
      },
    ],
    guesses: [
      { label: "列出电话为空企业", body: "可输出联系电话为空的企业名称、法人、注册地址、行业和最近更新日期。", chart: "table" },
      { label: "联系方式质量占比", body: "可按缺失、错误、重复、停用等类型生成占比图，评估数据质量。", chart: "pie" },
      { label: "生成联系方式治理表", body: "治理表建议包含企业名称、问题类型、责任人、处理状态和预计完成时间。", chart: "table" },
    ],
  },
  {
    id: "cancelled-industry",
    title: "已注销企业行业分布",
    keywords: ["注销", "已注销", "企业", "行业", "分布", "统计"],
    source: "企业注销登记数据",
    creator: "工商核查",
    createdAt: "2026-08-03 11:48",
    chartTitle: "已注销企业行业分布",
    defaultChart: "pie",
    displayCharts: ["pie"],
    tableHeaders: ["序号", "行业", "注销企业数量（家）"],
    chartData: [
      { label: "批发零售", value: 6, group: "商贸", columns: ["1", "批发零售", "6"] },
      { label: "餐饮住宿", value: 4, group: "服务", columns: ["2", "餐饮住宿", "4"] },
      { label: "商务服务", value: 3, group: "服务", columns: ["3", "商务服务", "3"] },
      { label: "建筑装饰", value: 2, group: "建筑", columns: ["4", "建筑装饰", "2"] },
      { label: "软件服务", value: 1, group: "科技", columns: ["5", "软件服务", "1"] },
    ],
    sections: [
      {
        heading: "一、查询结果",
        body: "已注销企业主要集中在批发零售和餐饮住宿行业，两类合计占比较高。",
      },
      {
        heading: "二、数据解读",
        bullets: [
          "注销行业分布可反映部分行业主体退出情况。",
          "需结合成立年限、区域和注册资本判断注销特征。",
          "短期集中注销行业可进一步分析政策、市场或经营环境影响。",
        ],
      },
    ],
    guesses: [
      { label: "列出批发零售注销企业", body: "可输出批发零售行业已注销企业名称、注销日期、成立年限和法人姓名。", chart: "table" },
      { label: "按成立年限看注销", body: "可按成立1年内、1-3年、3-5年、5年以上统计注销企业数量。", chart: "bar" },
      { label: "注销原因分类", body: "可按主动注销、经营停止、合并注销、吊销转注销等原因进行分类。", chart: "pie" },
    ],
  },
];
