window.aiDemoAnswers = [
  {
    id: "ops-dashboard",
    title: "经营看板本月关键指标解读",
    keywords: ["经营", "看板", "指标", "收入", "毛利", "费用", "利润"],
    source: "经营数据集市",
    creator: "数据运营",
    createdAt: "2026-07-27 09:20",
    chartTitle: "本月关键经营指标",
    defaultChart: "bar",
    displayCharts: ["bar"],
    chartData: [
      { label: "收入达成", value: 86, group: "达成率" },
      { label: "毛利率", value: 42, group: "利润" },
      { label: "费用率", value: 31, group: "费用" },
      { label: "回款率", value: 78, group: "现金" },
      { label: "订单转化", value: 64, group: "订单" },
      { label: "净利指数", value: 53, group: "利润" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "本月收入达成率正常，利润端承压。主要原因是费用率上升、部分高毛利订单延后确认，回款率尚未同步改善。",
      },
      {
        heading: "二、建议",
        bullets: [
          "优先核对高金额订单的交付和收入确认状态。",
          "拆分费用率上升来源，区分固定投入和临时项目费用。",
          "对回款率低于 75% 的区域增加催收跟进。",
        ],
      },
    ],
    guesses: [
      { label: "哪些指标低于目标？", body: "毛利率、费用率和净利指数需要重点关注。收入达成虽然接近目标，但利润质量不够稳定。", chart: "table" },
      { label: "按部门拆解费用", body: "建议按销售、交付、研发、职能四类拆分费用，并标记一次性费用，避免误判长期成本水平。", chart: "pie" },
      { label: "生成经营摘要", body: "本月收入推进正常，利润端受费用上升和订单结构影响。建议先处理高费用部门和高金额未确认订单。", chart: "bar" },
    ],
  },
  {
    id: "ar-risk",
    title: "应收账款逾期风险分析",
    keywords: ["应收", "账款", "逾期", "回款", "风险", "客户", "账龄"],
    source: "财务应收明细",
    creator: "财务分析",
    createdAt: "2026-07-26 16:10",
    chartTitle: "应收账龄分布",
    defaultChart: "pie",
    displayCharts: ["pie"],
    chartData: [
      { label: "30天内", value: 46, group: "正常" },
      { label: "31-60天", value: 24, group: "关注" },
      { label: "61-90天", value: 17, group: "风险" },
      { label: "90天以上", value: 13, group: "高风险" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "当前应收主要集中在 30 天内，但 61 天以上账龄占比已接近三成，需要按客户信用、合同节点和发票状态做穿透。",
      },
      {
        heading: "二、建议",
        bullets: [
          "90 天以上账款进入专项催收清单。",
          "对 61-90 天客户核查验收单、发票和付款审批状态。",
          "新签合同增加付款节点预警，降低账龄后移。",
        ],
      },
    ],
    guesses: [
      { label: "列出高风险账龄", body: "90 天以上为高风险账龄，61-90 天为观察账龄。建议分别设置责任人和预计回款日期。", chart: "table" },
      { label: "回款风险怎么分层？", body: "可按账龄、客户信用、历史逾期次数、合同金额和当前履约状态进行分层。", chart: "radar" },
      { label: "生成催收优先级", body: "优先处理金额大、账龄长、历史逾期多且当前无明确付款计划的客户。", chart: "bar" },
    ],
  },
  {
    id: "purchase-otd",
    title: "采购交付准时率波动原因",
    keywords: ["采购", "交付", "准时率", "供应商", "到货", "延期", "订单"],
    source: "采购订单台账",
    creator: "供应链分析",
    createdAt: "2026-07-25 13:45",
    chartTitle: "供应商准时交付率",
    defaultChart: "line",
    displayCharts: ["bar"],
    chartData: [
      { label: "1月", value: 91, group: "OTD" },
      { label: "2月", value: 88, group: "OTD" },
      { label: "3月", value: 90, group: "OTD" },
      { label: "4月", value: 82, group: "OTD" },
      { label: "5月", value: 79, group: "OTD" },
      { label: "6月", value: 84, group: "OTD" },
      { label: "7月", value: 86, group: "OTD" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "4-5 月准时率下滑明显，主要集中在定制件和长周期物料。7 月已有恢复，但仍低于年初水平。",
      },
      {
        heading: "二、建议",
        bullets: [
          "对延期次数高的供应商增加周度交付确认。",
          "长周期物料提前锁定需求，减少临时插单。",
          "把采购延期和生产缺料联动看，避免只看采购端指标。",
        ],
      },
    ],
    guesses: [
      { label: "哪些供应商拖期？", body: "建议按供应商统计延期次数、延期天数和影响订单金额，优先处理影响生产计划的供应商。", chart: "table" },
      { label: "准时率趋势如何？", body: "4-5 月为低点，6-7 月逐步恢复，但仍需要观察关键物料的稳定性。", chart: "line" },
      { label: "给出采购改进动作", body: "建立长周期物料安全提前期、供应商周度确认、异常订单升级和替代供应商池。", chart: "bar" },
    ],
  },
  {
    id: "yield-trace",
    title: "生产良率异常批次追踪",
    keywords: ["生产", "良率", "异常", "批次", "工序", "质检", "返工"],
    source: "MES 生产质量明细",
    creator: "质量分析",
    createdAt: "2026-07-24 11:05",
    chartTitle: "关键工序良率",
    defaultChart: "radar",
    displayCharts: ["table"],
    chartData: [
      { label: "来料检验", value: 94, group: "工序" },
      { label: "装配", value: 87, group: "工序" },
      { label: "调试", value: 81, group: "工序" },
      { label: "老化", value: 89, group: "工序" },
      { label: "终检", value: 92, group: "工序" },
      { label: "包装", value: 97, group: "工序" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "良率异常主要出现在调试和装配工序，疑似与批次物料差异、工装状态和操作参数有关。",
      },
      {
        heading: "二、建议",
        bullets: [
          "锁定异常批次，回看物料批号和工装编号。",
          "对调试失败原因做代码化归类，减少人工备注差异。",
          "将返工率和良率一起看，避免只看最终通过率。",
        ],
      },
    ],
    guesses: [
      { label: "异常集中在哪个工序？", body: "调试工序良率最低，其次是装配。建议先排查调试参数和装配工装状态。", chart: "radar" },
      { label: "输出异常批次表", body: "异常批次表应包含批次号、物料批号、工序、失败原因、返工次数、责任班组和处理状态。", chart: "table" },
      { label: "如何降低返工？", body: "先规范失败原因记录，再对高频失败项设置预检点，最后把异常批次纳入班组复盘。", chart: "bar" },
    ],
  },
  {
    id: "stock-turnover",
    title: "库存周转天数结构拆解",
    keywords: ["库存", "周转", "库存天数", "呆滞", "SKU", "仓库", "物料"],
    source: "库存余额与出入库流水",
    creator: "仓储分析",
    createdAt: "2026-07-23 10:35",
    chartTitle: "重点品类库存周转天数",
    defaultChart: "bar",
    displayCharts: ["bar"],
    chartData: [
      { label: "核心料", value: 38, group: "物料" },
      { label: "结构件", value: 56, group: "物料" },
      { label: "包材", value: 27, group: "物料" },
      { label: "备件", value: 73, group: "物料" },
      { label: "低值耗材", value: 19, group: "物料" },
      { label: "定制件", value: 86, group: "物料" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "定制件和备件周转天数偏高，存在库存占用风险。包材和低值耗材周转较快，需要关注短期缺货。",
      },
      {
        heading: "二、建议",
        bullets: [
          "定制件按项目状态拆分可用库存和锁定库存。",
          "备件区分安全库存与长期未动销库存。",
          "高周转低库存品类设置补货提醒。",
        ],
      },
    ],
    guesses: [
      { label: "哪些物料占用高？", body: "定制件和备件占用较高，建议结合项目交付计划判断是否需要转储或消耗。", chart: "table" },
      { label: "库存结构占比", body: "可按核心料、结构件、包材、备件、耗材和定制件拆分库存金额占比。", chart: "pie" },
      { label: "生成补货建议", body: "低值耗材和包材适合设置自动补货阈值，定制件不建议简单按历史消耗补货。", chart: "bar" },
    ],
  },
  {
    id: "contract-risk",
    title: "合同履约进度风险预警",
    keywords: ["合同", "履约", "进度", "风险", "里程碑", "验收", "交付"],
    source: "合同与项目履约数据",
    creator: "项目分析",
    createdAt: "2026-07-22 15:30",
    chartTitle: "合同里程碑完成率",
    defaultChart: "area",
    displayCharts: ["table"],
    chartData: [
      { label: "启动", value: 96, group: "里程碑" },
      { label: "方案", value: 88, group: "里程碑" },
      { label: "实施", value: 72, group: "里程碑" },
      { label: "联调", value: 64, group: "里程碑" },
      { label: "验收", value: 51, group: "里程碑" },
      { label: "回款", value: 47, group: "里程碑" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "合同履约风险集中在联调、验收和回款阶段。若验收材料准备滞后，会直接影响收入确认和回款。",
      },
      {
        heading: "二、建议",
        bullets: [
          "对低于 70% 的里程碑建立红黄灯状态。",
          "验收前置材料清单，减少临近节点补资料。",
          "联动项目经理、交付负责人和财务回款计划。",
        ],
      },
    ],
    guesses: [
      { label: "哪些合同有延期风险？", body: "建议筛选联调和验收阶段低于计划 10 个百分点以上的合同，并按金额排序。", chart: "table" },
      { label: "履约卡在哪个环节？", body: "当前主要卡在联调到验收的转段，材料和客户确认节奏是关键影响项。", chart: "area" },
      { label: "生成预警规则", body: "里程碑延迟超过 7 天、验收材料缺失、回款节点无计划三类情况应触发预警。", chart: "radar" },
    ],
  },
  {
    id: "ticket-efficiency",
    title: "售后工单处理效率对比",
    keywords: ["售后", "工单", "效率", "SLA", "响应", "处理", "服务"],
    source: "售后服务工单",
    creator: "服务分析",
    createdAt: "2026-07-21 18:20",
    chartTitle: "工单处理效率",
    defaultChart: "line",
    displayCharts: ["bar"],
    chartData: [
      { label: "周一", value: 82, group: "效率" },
      { label: "周二", value: 85, group: "效率" },
      { label: "周三", value: 79, group: "效率" },
      { label: "周四", value: 76, group: "效率" },
      { label: "周五", value: 83, group: "效率" },
      { label: "周六", value: 71, group: "效率" },
      { label: "周日", value: 68, group: "效率" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "周末处理效率下降明显，主要与排班人数减少、复杂问题升级等待和备件响应有关。",
      },
      {
        heading: "二、建议",
        bullets: [
          "把高频问题沉淀为标准回复和处理模板。",
          "周末保留备件审批和二线支持值班。",
          "按问题类型拆分平均响应时间和平均解决时间。",
        ],
      },
    ],
    guesses: [
      { label: "哪天效率最低？", body: "周日效率最低，其次是周六。建议调整周末排班，并提前处理备件审批。", chart: "line" },
      { label: "按问题类型拆分", body: "建议拆分为账号权限、系统故障、使用咨询、数据问题和备件维修五类。", chart: "table" },
      { label: "如何提升SLA？", body: "先降低高频问题处理时长，再保障二线升级链路，最后按客户等级设置优先级。", chart: "bar" },
    ],
  },
  {
    id: "people-efficiency",
    title: "部门人效投入产出分析",
    keywords: ["人效", "部门", "投入", "产出", "工时", "效率", "成本"],
    source: "工时与产出数据",
    creator: "管理分析",
    createdAt: "2026-07-20 17:00",
    chartTitle: "部门人效指数",
    defaultChart: "radar",
    displayCharts: ["pie"],
    chartData: [
      { label: "销售", value: 78, group: "部门" },
      { label: "交付", value: 72, group: "部门" },
      { label: "研发", value: 69, group: "部门" },
      { label: "供应链", value: 74, group: "部门" },
      { label: "售后", value: 66, group: "部门" },
      { label: "职能", value: 58, group: "部门" },
    ],
    sections: [
      {
        heading: "一、结论",
        body: "销售和供应链人效相对较高，售后和职能偏低。需要结合工作量、人员结构和一次性专项投入判断。",
      },
      {
        heading: "二、建议",
        bullets: [
          "对低人效部门拆分常规工作和项目型工作。",
          "把工时投入与结果指标挂钩，不单独看人头数量。",
          "对跨部门支援工时做归集，避免产出归属偏差。",
        ],
      },
    ],
    guesses: [
      { label: "哪个部门人效偏低？", body: "职能和售后当前人效偏低，需要进一步拆分工作量来源和人员投入结构。", chart: "radar" },
      { label: "输出人效明细表", body: "明细表应包含部门、人数、工时、产出指标、人均产出、专项投入和说明。", chart: "table" },
      { label: "怎么提升人效？", body: "先减少重复人工流程，再把低价值手工统计自动化，最后优化跨部门协同边界。", chart: "bar" },
    ],
  },
];
